language: php

php:
  - '7.1'

env:
  APP_ENV: testing
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  APP_KEY: 'base64:zjb4qWfXaJt6dzIHzRxCmYzA4vJWbWFKAhE+Ya78Rbs='

branches:
  - master

install:
  - composer self-update
  - composer install --no-interaction

script:
  - composer test